### ISSUE TITLE
No mist.ini detect for VGA

### ISSUE THREAD

**Issue by ManuFerHi** [nippur72/Laser500_MiST#1]
It does not recognize the mist.ini switches, you have to connect the disable_scandoubler and YPbPr signals to the corresponding status () switches so that the mist.ini is read

**Comment by nippur72** [comment]
~~oops! `scandoubler_disable` and `ypbpr` are unconnected wires 😲~~

**Comment by nippur72** [comment]
I just checked the code and the wires are connected, `scandoubler_disable` and `ypbpr` are outputs of the module `userio.v`.

I also checked on the Mistica by changing the `mist.ini` and it is working.

**Comment by ManuFerHi** [comment]
Right, I just tried it and it looks at 15khz but it doesn't work at vga 31khz

**Comment by ManuFerHi** [comment]
Also tested by other people, it seems that VGA does not work.

**Comment by nippur72** [comment]
you are right there is some issue with the VGA signal. I'll investigate it, thanks

**Comment by nippur72** [comment]
I fixed it, it was the hsync width too short on the scandoubler (`SD_HCNT_WIDTH` parameter). Increasing it from 9 to 11 fixed it. Thanks for reporting.
